services:
    # catalogue:
    #     build: 
    #         dockerfile: Dockerfile
    #     image: catalogue:1.0.0 
    #     container_name: catalogue
    #     depends_on: 
    #         - mongodb
    mongodb:
        build:
            dockerfile: ./mongodb.Dockerfile # it moves to mongodb directory
        image: ramcharankola2/mongodb:1.0.0 # docker build -t ramcharankola2/mongodb:1.0.0
        container_name: mongodb

networks:
    default:
        driver: bridge
        name: roboshop
        external: false # if true, you need to create network manually
