services:
    catalogue:
        build: 
            context: ./catalogue
            dockerfile: Dockerfile
        image: catalogue:1.0.0 
        container_name: catalogue
        depends_on: 
            - mongodb
    user: 
        build: ./user # shorthand for dockerfile: Dockerfile, directly went to Dockerfile in user folder then run "docker build -t" with below image name. In backend Docker convert this command into "context & Dockerfile with location"
        image: user:1.0.0
        container_name: user
        depends_on:
            - mongodb
            - redis
    cart:
        build: ./cart
        image: cart:1.0.0
        container_name: cart
        depends_on:
            - redis
            - rabbitmq
    shipping:
        build: ./shipping
        image: shipping:1.0.0
        container_name: shipping
        depends_on:
         - mysql
    payment:
        build: ./payment
        image: payment:1.0.0
        container_name: payment
        depends_on:
            - mysql
            - rabbitmq
    frontend:
        build: ./frontend
        image: frontend:1.0.0
        container_name: frontend
        depends_on:
            - catalogue
            - user
    mongodb:
        build:
            context: ./mongodb
            dockerfile: Dockerfile # it moves to mongodb directory
        image: mongodb:1.0.0 # docker build -t mongodb:1.0.0
        container_name: mongodb
    redis:
        image: redis:7.0
        container_name: redis
    mysql:
        build: ./mysql
        image: mysql:1.0.0
        container_name: mysql
    rabbitmq:
        image: rabbitmq:3
        container_name: rabbitmq

networks:
    default:
        driver: bridge
        name: roboshop
        external: false # if true, you need to create network manually
